// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIn98L3vq586N5Dpvfo9zzMYN1o3QwFUM',
    appId: '1:747156391513:web:c52305bf4b9e0f6a475348',
    messagingSenderId: '747156391513',
    projectId: 'projeto-integrador-iv-6b106',
    authDomain: 'projeto-integrador-iv-6b106.firebaseapp.com',
    storageBucket: 'projeto-integrador-iv-6b106.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAztx9_bY9CjXGRknRvhwjl5XkRJFtgg0c',
    appId: '1:747156391513:android:8b0fa825855c9300475348',
    messagingSenderId: '747156391513',
    projectId: 'projeto-integrador-iv-6b106',
    storageBucket: 'projeto-integrador-iv-6b106.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHD44p7IJ-KYdz9fxl7Go2YDtamDQ33CE',
    appId: '1:747156391513:ios:244b2054e55dcbf8475348',
    messagingSenderId: '747156391513',
    projectId: 'projeto-integrador-iv-6b106',
    storageBucket: 'projeto-integrador-iv-6b106.appspot.com',
    iosClientId: '747156391513-70c5oo771hmnllcp6olkqkuimv5uet95.apps.googleusercontent.com',
    iosBundleId: 'com.puc.projiv.governance.projivGov',
  );
}
